languages:
  Python: true
engines:
  pep8:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
exclude_paths:
- versioneer.py
- efel/_version.py
- docs/source/conf.py
- efel/tests
