engines:
  pep8:
    enabled: true
    checks:
        E501:
            enabled: false
        E402:
            enabled: false
ratings:
    paths:
        - "**.py"
exclude_paths:
- versioneer.py
- efel/_version.py
- docs/source/conf.py
- efel/tests
- examples
