language: python
python:
  - '2.6'
  - '2.7'
script: make test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8ae38b9a790ed3e31c7a
    on_success: change
    on_failure: change
    on_start: false
cache: pip
deploy:
  provider: pypi
  user: wvangeit
  password:
    secure: jHnj/T6sANjIHvvJenBwThkpFZRb9lyAirzt1aXwuBWYiFQ8ojrapIOr/wf5hAtMgAPMGUgdV315g53ZawKFBuHmTuDuhnFyqyH07wha/licvga3o7juPFaIIvYN5SeOGygvrxCtMKx5p/VzWuhf04pKJMqGqE2lj4RDwwmGIjY=
