language: python
python:
    - "2.7"
script: make test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8ae38b9a790ed3e31c7a
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false
