version: 1.0.{build}
build:
  verbosity: minimal
environment:
  matrix:
    - PYTHON: "C:\\Python27"
build_script:
    - "python setup.py build"
test_script:
    - "pip install nose coverage --upgrade"
    - "python setup.py nosetests"
