version: 1.0.{build}
build:
  verbosity: minimal
environment:
  matrix:
    - PYTHON: "C:\\Python27"
build_script:
    - "python -m pip install pip --upgrade"
    - "python setup.py build bdist_wheel"
test_script:
    - "python -m pip install nose coverage --upgrade"
    - "python setup.py nosetests"
