name: Build

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  call-test-workflow:
    uses: BlueBrain/eFEL/.github/workflows/test.yml@master
  
  wheels:
    needs: call-test-workflow
    name: Build wheels for ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [cp36, cp37, cp38, cp39, cp310]
        arch: [x86_64, amd64, 32]
        exclude:
          - os: macos-latest
            arch: amd64
          - os: macos-latest
            arch: 32
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-latest
            arch: 32
          - os: windows-latest
            arch: x86_64
          # dropping support for windows 32bit for python >=3.10
          - os: windows-latest
            arch: 32
            python: cp310
    env:
      CIBW_BUILD: ${{ matrix.python }}*${{ matrix.arch }}
      CIBW_TEST_REQUIRES: pytest neo[neomatlabio]>=0.5.1
      CIBW_TEST_COMMAND: pytest -sx {project}/efel/tests
      CIBW_SKIP: "*-musllinux_*"
      
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install cibuildwheel
        run: pip install cibuildwheel
      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
  
  tarball:
    name: Build tarball
    runs-on: ubuntu-latest
    needs: call-test-workflow
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Build a source tarball
        run:
            python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: dist


  publish:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    needs: [call-test-workflow, wheels, tarball]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Put artifacts into dist directory
        run: |
          mkdir -p dist
          find artifacts -type f \( -iname \*.whl -o -iname \*.tar.gz \) -exec mv {} dist \;

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}